SubscriptionJournals/Models/LogInViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SubscriptionJournals.Models
{
    public class LogInViewModel
    {
        [MaxLength(80)]
        [Required(ErrorMessage = "Required Email Address Field")]
        [DisplayName("E-mail")]
        [Column(TypeName = "nvarchar(80)")]
        public string email { get; set; }

        [MaxLength(100)]
        [Required(ErrorMessage = "Required Password Field")]
        [DisplayName("Password")]
        [Column(TypeName = "nvarchar(100)")]
        public string Password { get; set; }
        [DisplayName("Remember Me")]
        public bool RememberMe { get; set; }
    }
}

SubscriptionJournals/Controllers/UsersViewModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SubscriptionJournals;
using SubscriptionJournals.Models;
using SubscriptionJournals.Tools;

namespace SubscriptionJournals.Controllers
{
    public class UsersViewModelController : BaseController
    {
        //DBContext dependency Injection
        private readonly ApplicationDbContext _context;

        public UsersViewModelController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UsersViewModel
        public async Task<IActionResult> Index()
        {
            //return View(await _context.Users.ToListAsync());DeleteCookies();
            HttpContext.Session.Clear();
            return RedirectToAction("Login", "Account");
        }

        // GET: JournalsViewModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {            
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            //if session variable is not equal to id
            if(id_user != 0)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var usersViewModel = await _context.Users.FirstOrDefaultAsync(m => m.user_Id == id);
                if (usersViewModel == null)
                {
                    return NotFound();
                }
                if (id_user == id)
                {
                    //current user is viewing his data
                    ViewBag.CurrentUser = "True";
                    return View(usersViewModel);
                }
                else
                {
                    //another user is viewing the data                
                    var verifysubscirption = await _context.Subscriptions.Where(x => x.subscriptor == id_user && x.subscribesTo == id).Select(x => x.subscribesTo).FirstOrDefaultAsync();
                    if (!string.IsNullOrEmpty(verifysubscirption.ToString()) || verifysubscirption != 0)
                    {
                        //is a follower of the current user
                        ViewBag.Follower = "True";
                        return View(usersViewModel);
                    }
                    return View(usersViewModel);
                }
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }

        }
        public async Task<IActionResult> DetailsForUsers(int? id)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            //if session variable is not equal to id
            if (id_user != 0)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var usersViewModel = await _context.Users.FirstOrDefaultAsync(m => m.user_Id == id);
                if (usersViewModel == null)
                {
                    return NotFound();
                }
                if (id_user == id)
                {
                    //current user is viewing his data
                    ViewBag.CurrentUser = "True";
                    return View(usersViewModel);
                }
                else
                {
                    //another user is viewing the data                
                    var verifysubscirption = await _context.Subscriptions.Where(x => x.subscriptor == id_user && x.subscribesTo == id).Select(x => x.subscribesTo).FirstOrDefaultAsync();
                    if (verifysubscirption != 0)
                    {
                        //is a follower of the current user
                        ViewBag.Follower = "True";
                        return View(usersViewModel);
                    }
                    return View(usersViewModel);
                }
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }

        }

        // GET: UsersViewModel/Create
        public IActionResult Create()
        {
                return View();
        }

        // POST: UsersViewModel/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string user,[Bind("user_Id,user,name,Password,lastName,email,token,creationDate,followers,following,journalsPublished")] UsersViewModel usersViewModel)
        {
                if (ModelState.IsValid)
                {
                    //(Initialize) add default values to this fields to prevent Bugs with data
                    usersViewModel.creationDate = DateTime.Now;
                    usersViewModel.followers = 0;
                    usersViewModel.following = 0;
                    usersViewModel.journalsPublished = 0;
                    //hashing the password provided by user
                    usersViewModel.Password = HashPassword.HashPass(usersViewModel.Password);
                    //generating token for recover password
                    var userTokenStr = GenerateUserToken.RandomString();
                    //hashing the token for security purposes
                    usersViewModel.token = HashPassword.HashPass(userTokenStr);
                    _context.Add(usersViewModel);
                    await _context.SaveChangesAsync();
                    Notify("Success", "User Created Successfully", notificationType: Notifications.NotificationType.success);
                    //get the id from current user registered
                    var id = await _context.Users.Where(x => x.user == user).Select(x => x.user_Id).FirstOrDefaultAsync();
                    //return RedirectToAction("Edit", new { id = id });
                return RedirectToAction("Login", "Account");
                }
                return View(usersViewModel);
            
        }

       

        // GET: UsersViewModel/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var usersViewModel = await _context.Users.FindAsync(id);
                if (usersViewModel == null)
                {
                    return NotFound();
                }
                return View(usersViewModel);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: UsersViewModel/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string token, DateTime creationDate, string Password, [Bind("user_Id,user,Password,name,lastName,email,token,creationDate,followers,following,journalsPublished,NewPassword")] UsersViewModel usersViewModel)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                if (id != usersViewModel.user_Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        if (!string.IsNullOrEmpty(usersViewModel.NewPassword))
                        {
                            usersViewModel.NewPassword = HashPassword.HashPass(usersViewModel.NewPassword);
                            if (Password != usersViewModel.NewPassword)
                            {
                                usersViewModel.Password = usersViewModel.NewPassword;
                                _context.Update(usersViewModel);
                                await _context.SaveChangesAsync();
                                Notify("Success", "User Update Success", notificationType: Notifications.NotificationType.success);
                                return RedirectToAction("Index", "JournalsViewModel");
                            }
                            else
                            {
                                if (Password == usersViewModel.Password)
                                {
                                    Notify("Error", "You can't use the same password, please try again with another one", notificationType: Notifications.NotificationType.error);
                                    return RedirectToAction("Edit");
                                }
                            }
                        }
                        else
                        {
                            usersViewModel.Password = Password;
                            _context.Update(usersViewModel);
                            await _context.SaveChangesAsync();
                            //Notify("Success", "User Update data Success", notificationType: Notifications.NotificationType.success);
                            return RedirectToAction("Index", "JournalsViewModel");
                        }
                    }
                    catch (DbUpdateConcurrencyException)
                    {

SubscriptionJournals/Views/Shared/_Feed.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubscriptionJournals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SubscriptionJournals</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SubscriptionJournals - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SubscriptionJournals/Views/Shared/_Forms.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet" />

</head>

<body class="bg-gradient-primary">
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-newspaper"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Journalify</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="JournalsViewModel" asp-action="Index">
                    <i class="fas fa-home"></i>
                    <span>Home</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Journals
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-copy"></i>
                    <span>Posts</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Posts Tools</h6>
                        <a class="collapse-item" asp-controller="JournalsViewModel" asp-action="Create">New Journal Post</a>
                        <a class="collapse-item" asp-controller="JournalsViewModel" asp-action="IndexMyPosts">My Posts</a>
                        <a class="collapse-item" asp-controller="JournalsViewModel" asp-action="IndexFollowing">Subscriptions Posts</a>
                    </div>
                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Account Settings
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-user"></i>
                    <span>Account</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Login Screens:</h6>
                        <a class="collapse-item" asp-controller="UsersViewModel" asp-action="Edit" asp-route-id="@Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetInt32("Id"))">Edit Account</a>
                        <a class="collapse-item" asp-controller="UsersViewModel" asp-action="Delete" asp-route-id="@Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetInt32("Id"))">Delete Account</a>
                        <div class="collapse-divider"></div>
                    </div>
                </div>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <form class="form-inline">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                    </form>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">



                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@HttpContextAccessor.HttpContext.Session.GetString("UserName");</span>
                                <img class="~/img-profile rounded-circle"
                                     src="~/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="UsersViewModel" asp-action="Details" asp-route-id="@Convert.ToInt32(HttpContextAccessor.HttpContext.Session.GetInt32("Id"))">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Account" asp-action="Login" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Journals</h1>
                    <p class="mb-4">
                        Journals are files uploaded by users to consume for our community.
                    </p>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">All Posts</h6>
                        </div>
                        <div class="card-body">
                            <div class="container">
                                <main role="main" class="pb-3">
                                    @RenderBody()
                                </main>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" asp-action="Login" asp-controller="Account">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @await Html.PartialAsync("_NotificationsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SubscriptionJournals/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SubscriptionJournals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SubscriptionJournals</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SubscriptionJournals - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SubscriptionJournals/Views/Shared/_LogIn.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->

                        <div class="container">
                            <main role="main" class="pb-3">
                                @RenderBody()
                            </main>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @await Html.PartialAsync("_NotificationsPartial")
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

SubscriptionJournals/Views/Shared/_NotificationsPartial.cshtml
<script>
    var msg = @(TempData["Message"]!=null? Html.Raw(TempData["Message"]) : Html.Raw("undefined"));

    console.log(msg);

    if (msg) {
        if (msg.provider == "sweetAlert") {
            Swal.fire({
                title: msg.title,
                text: msg.text,
                icon: msg.icon
            })
        } else {
            toastr[msg.type](msg.text, msg.title);
        }
    }
</script>