SubscriptionJournals/Controllers/JournalsViewModelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SubscriptionJournals;
using SubscriptionJournals.Models;
using SubscriptionJournals.Tools;

namespace SubscriptionJournals.Controllers
{
    public class JournalsViewModelController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public JournalsViewModelController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: JournalsViewModels
        public async Task<IActionResult> Index()
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                var Posts = await _context.Journals.Include(j => j.Users).ToListAsync();
                return View(Posts);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear(); 
                return RedirectToAction("Login", "Account");
            }
            
        }
        public async Task<IActionResult> IndexMyPosts()
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                var Posts = await _context.Journals.Where(x => x.author == id_user).Include(j => j.Users).ToListAsync();
                return View(Posts);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }
        }
        public async Task<IActionResult> IndexFollowing()
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                
                var PostFollowing = await (from subs in _context.Subscriptions
                                           join Jour in _context.Journals
                                           on subs.subscribesTo equals Jour.author
                                           join User in _context.Users
                                           on Jour.author equals User.user_Id
                                           select new IndexFollowersViewModel
                                           {
                                               name = Jour.name,
                                               creationDate = Jour.creationDate,
                                               user = User.user,
                                               journal_Id = Jour.journal_Id,
                                               user_Id = User.user_Id,
                                               subscribesTo = subs.subscribesTo,
                                               subscriptor = subs.subscriptor
                                           }).Where(x => x.subscriptor == id_user).ToListAsync();

                return View(PostFollowing);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }

        }
        //}
        // GET: JournalsViewModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var journalsViewModel = await _context.Journals
                    .Include(j => j.Users)
                    .FirstOrDefaultAsync(m => m.journal_Id == id);
                if (journalsViewModel == null)
                {
                    return NotFound();
                }

                return View(journalsViewModel);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }
        }

        // GET: JournalsViewModels/Create
        public IActionResult Create()
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                return View();
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: JournalsViewModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("journal_Id,name,author,creationDate,path,pdf")] JournalsViewModel journalsViewModel)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                if (ModelState.IsValid)
                {
                    if (journalsViewModel.pdf != null)
                    {
                        string folder = "journals/";
                        journalsViewModel.path = await UploadPDF(folder, journalsViewModel.pdf);
                    }
                    journalsViewModel.author = id_user;
                    journalsViewModel.creationDate = DateTime.Now;
                    _context.Add(journalsViewModel);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(journalsViewModel);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }

        }

        // GET: JournalsViewModels/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var journalsViewModel = await _context.Journals.FindAsync(id);
        //    if (journalsViewModel == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["author"] = new SelectList(_context.Users, "user_Id", "name", journalsViewModel.author);
        //    return View(journalsViewModel);
        //}

        //// POST: JournalsViewModels/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("journal_Id,name,author,creationDate,path")] JournalsViewModel journalsViewModel)
        //{
        //    if (id != journalsViewModel.journal_Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(journalsViewModel);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!JournalsViewModelExists(journalsViewModel.journal_Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["author"] = new SelectList(_context.Users, "user_Id", "name", journalsViewModel.author);
        //    return View(journalsViewModel);
        //}

        // GET: JournalsViewModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var journalsViewModel = await _context.Journals
                    .Include(j => j.Users)
                    .FirstOrDefaultAsync(m => m.journal_Id == id);
                if (journalsViewModel == null)
                {
                    return NotFound();
                }

                return View(journalsViewModel);
            }
            else
            {
                DeleteCookies();
                HttpContext.Session.Clear();
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: JournalsViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            int id_user = Convert.ToInt32(HttpContext.Session.GetInt32("Id"));
            if(id_user != 0)
            {
                var journalsViewModel = await _context.Journals.FindAsync(id);
                var filepath = _context.Journals.Where(x => x.journal_Id == id).Select(x => x.path).FirstOrDefault();
                if (filepath != null)
                {
                    string wwwpath = this._hostingEnvironment.WebRootPath;
                    string serverFolder = wwwpath + filepath;
                    System.IO.File.Delete(serverFolder);

SubscriptionJournals/Views/UsersViewModel/Create.cshtml
@model SubscriptionJournals.Models.UsersViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Forms.cshtml";
}
<title>Register Account</title>
<div class="row">
    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
    <div class="col-lg-7">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
            </div>
            <form asp-action="Create" class="user">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" asp-for="name" class="form-control form-control-user" placeholder="First Name" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <input type="text" asp-for="lastName" class="form-control form-control-user" placeholder="Last Name" />
                        <span asp-validation-for="lastName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <input type="email" asp-for="email" class="form-control form-control-user" placeholder="Email Address" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" asp-for="user" class="form-control form-control-user" placeholder="User Name (Alias)" />
                        <span asp-validation-for="user" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <input type="password" asp-for="Password" class="form-control form-control-user" placeholder="Password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <input type="submit" value="Create" class="btn btn-primary btn-user btn-block" />
                <hr>
            </form>
            <hr>
            <div class="text-center">
                <a class="small" asp-action="Login" asp-controller="AccountController">Already have an account? Login!</a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubscriptionJournals/Views/UsersViewModel/Delete.cshtml
@model SubscriptionJournals.Models.UsersViewModel

@{
    ViewData["Title"] = "DeleteConfirmed";
    Layout = "~/Views/Shared/_Forms.cshtml";
}

<title>Confirm Delete</title>

<h3>Are you sure you want to delete this account?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.user)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.user)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.creationDate)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.creationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.followers)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.followers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.following)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.following)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.journalsPublished)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.journalsPublished)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="user_Id" />
        <input type="submit" value="Delete" class="btn btn-danger btn-block" /> 
        <a asp-action="Index" asp-controller="JournalsViewModel" class="btn btn-danger">Go Home</a>
    </form>
</div>

SubscriptionJournals/Views/UsersViewModel/Details.cshtml
@model SubscriptionJournals.Models.UsersViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Forms.cshtml";
}

<h1>@Html.DisplayFor(model => model.user)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.creationDate)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.creationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.followers)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.followers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.following)
        </dt>
        <dd class = "col-sm-4">
            @Html.DisplayFor(model => model.following)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.journalsPublished)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.journalsPublished)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.user_Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SubscriptionJournals/Views/UsersViewModel/DetailsForUsers.cshtml
@model SubscriptionJournals.Models.UsersViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Forms.cshtml";
}<title>User Info</title>

<h1>@Html.DisplayFor(model => model.user)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.creationDate)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.creationDate)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.followers)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.followers)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.following)
        </dt>
        <dd class="col-sm-4">
            @Html.DisplayFor(model => model.following)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.journalsPublished)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.journalsPublished)
        </dd>*@
    </dl>
</div>
<div>
    @**@
    @{ if (ViewBag.CurrentUser == "True")
        {
            <a asp-action="Edit" asp-route-id="@Model.user_Id" class="btn btn-outline-info" >Edit</a>
            <a asp-action="Index" asp-controller="JournalsViewModel" class="btn btn-outline-warning"> Go To Home</a>
        }
        else
        {
            if (ViewBag.Follower != "True")
            {
                <a asp-action="Subscribe" asp-controller="JournalsViewModel" asp-route-id="@Model.user_Id" class="btn btn-outline-success">Seguir</a>
            }
            else
            {
                <a asp-action="UnSuscribe" asp-controller="JournalsViewModel" asp-route-id="@Model.user_Id" class="btn btn-outline-danger">Dejar de Seguir</a>
            }
        }

    }


</div>

SubscriptionJournals/Views/UsersViewModel/Edit.cshtml
@model SubscriptionJournals.Models.UsersViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Forms.cshtml";
}
<title>Edit Account</title>
<div class="row">
    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
    <div class="col-lg-7">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
            </div>
            <form asp-action="Edit" class="user">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="user_Id" />
                <input type="hidden" asp-for="token" />
                <input type="hidden" asp-for="creationDate" />
                <input type="hidden" asp-for="followers" />
                <input type="hidden" asp-for="following" />
                <input type="hidden" asp-for="journalsPublished" />
                <input type="hidden" asp-for="Password" />
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" asp-for="name" class="form-control form-control-user" placeholder="First Name" />
                        <span asp-validation-for="name" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <input type="text" asp-for="lastName" class="form-control form-control-user" placeholder="Last Name" />
                        <span asp-validation-for="lastName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <input type="email" asp-for="email" class="form-control form-control-user" placeholder="Email Address" />
                    <span asp-validation-for="email" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" asp-for="user" class="form-control form-control-user" placeholder="User Name (Alias)" />
                        <span asp-validation-for="user" class="text-danger"></span>
                    </div>
                    <div class="col-sm-6">
                        <input type="password" asp-for="NewPassword" class="form-control form-control-user" placeholder="Password" />
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                </div>
                <input type="submit" value="Save" class="btn btn-primary btn-user btn-block" />
                <hr>
                <hr>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SubscriptionJournals/Views/UsersViewModel/Index.cshtml
@*@model IEnumerable<SubscriptionJournals.Models.UsersViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Tables.cshtml";
}


<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.user)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.lastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.creationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.followers)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.following)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.journalsPublished)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.user)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.lastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.creationDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.followers)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.following)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.journalsPublished)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.user_Id">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.user_Id">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.user_Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>*@